// TODO: Allow combinations with autogenerated files for current project context aware type hints!
// For example inside `defineTopic.contributors` we can typehint currently registered contributors just like Nuxt does with API hints!

declare global {
    const defineEruditConfig: typeof import('./types/erudit')['defineEruditConfig'];
    const defineContributor: typeof import('./types/contributor')['defineContributor'];
    const defineBook: typeof import('./types/content/book')['defineBook'];
    const defineGroup: typeof import('./types/content/group')['defineGroup'];
    const defineTopic: typeof import('./types/content/topic')['defineTopic'];
}

export { defineEruditConfig } from './types/erudit';
export { defineContributor } from './types/contributor';
export { defineBook } from './types/content/book';
export { defineGroup } from './types/content/group';
export { defineTopic } from './types/content/topic';